### ISSUE TITLE
Parameters for indoor reconstruction

### ISSUE THREAD

**Issue by satyajitghana** [houfei0801/ipsr#1]
What are the parameters for the below reconstruction?

![image](https://user-images.githubusercontent.com/8092481/214234671-15ab6519-eaaf-438c-b998-2526c5f27415.png)

And can i get the point cloud used for it. I want to reproduce your results.

**Comment by houfei0801** [comment]
You can download the data here and use the default parameters.
https://drive.google.com/file/d/0B-ePgl6HF260N0tCdzA2Zm5JdTQ/view?resourcekey=0-JMwfqI8eYnmH0Dzyg20Lew
