### ISSUE TITLE
Holes in generated mesh

### ISSUE THREAD

**Issue by liuzhongshu** [houfei0801/ipsr#3]
I am trying to reconstruct a 3d point cloud with ipsr

ipsr --in pointcloud.ply --out output.ply

but the output mesh has many holes, like this:
<img width="812" alt="image" src="https://github.com/houfei0801/ipsr/assets/458996/1b02938f-90ed-4b5e-aa35-fe8c89c7398d">

I'm wondering if I've set the wrong parameter or if this type of point cloud can't be supported.

**Comment by houfei0801** [comment]
What is your point cloud? Are your model non-watertight?

**Comment by liuzhongshu** [comment]
It's a volumetric data from medical imaging.  I have send you a sample.

**Comment by houfei0801** [comment]
The points should distribute on a surface for surface reconstruction. But, in your volume data, the model interior is full of points, so it is not applicable.

**Comment by liuzhongshu** [comment]
Thanks.

I'll try some other algorithms.
