### ISSUE TITLE
sample_points function

### ISSUE THREAD

**Issue by jaquilio** [houfei0801/ipsr#4]
The code calls the sample_points function in PoissonRecon.inl. What purpose does that sample_points function achieve?

**Comment by houfei0801** [comment]
Sample points on an adaptive Octree. This is a step of the [PoissonRecon](https://github.com/mkazhdan/PoissonRecon).

**Comment by jaquilio** [comment]
I searched all of the code at that link and no occurrence of sample_points was found.

**Comment by jaquilio** [comment]
I searched the code at that link for the "sample_points" function, but, didn't find it.

**Comment by jaquilio** [comment]
I searched the code at the link, but, didn't find the function sample_points there.
